services:
  db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: auth-app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      DB_PORT: 5432
      JWT_SECRET: supersecreto123
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
    command: npm start

volumes:
  postgres_data: