services:
  db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - auth-network

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: auth-app
    environment:
      DB_HOST: pgbouncer
      DB_PORT: 6432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      JWT_SECRET: supersecreto123
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
    depends_on:
      - pgbouncer
    command: npm start
    networks:
      - auth-network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: auth-pgbouncer
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 100
      DEFAULT_POOL_SIZE: 20
    ports:
      - "6432:6432"
    depends_on:
      - db
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data: